package org.mourya.msscbeerorderservice.domain;

public enum  BeerOrderStatusEnum {
    NEW, VALIDATE, VALIDATION_EXCEPTION, ALLOCATED, ALLOCATION_EXCEPTION, PENDING_INVENTORY, PICKED_UP, DELIVERED, DELIVERED_EXCEPTION
}